I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 29, in script
    e "Once you add a story, pictures, and music, you can release it to the world!"
Exception: Sayer 'e' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 29, in script
    e "Once you add a story, pictures, and music, you can release it to the world!"
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 2586, in execute
    Say.execute(self)
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 583, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 472, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'e' is not defined.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
Kaua 1.0
Tue Apr 29 08:42:27 2025
